spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Papun@9348
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jakarta.persistence.jdbc.url:jdbc:mysql://mysqldb:3306/bluepal


